### ISSUE TITLE
Don't log element when every I switch tabs.

### ISSUE THREAD

**Issue by Pleasurazy** [sommerper/filetype-color#8]
This package let me get colorful tree view. I am happy.

But I have doubt for this:

https://github.com/sommerper/filetype-color/blob/master/lib/filetype-color-view.js#L148

![image](https://cloud.githubusercontent.com/assets/1500206/4941840/9580292a-65e6-11e4-8c5f-a454afcb89ae.png)

**Comment by Twintails** [comment]
There is a console.log in the filetype-color-view.js 
Users/user/.atom/packages/filetype-color/lib/filetype-color-view.js

on about line 148 - console.log(elements);

Workaround
You can comment it out and save the file. 
Then re-launch the project window (or atom)
Probably just a hold over from the plugin development.
